<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="8" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-09T07:43:44Z" name="Custom Listeners in TestNG" finished-at="2025-01-09T07:43:44Z" duration-ms="92">
    <groups>
      <group name="Regression">
        <method signature="TestCase01.regTest()[pri:1, instance:rough.TestCase01@3cce5371]" name="regTest" class="rough.TestCase01"/>
        <method signature="TestCase01.loginTest()[pri:0, instance:rough.TestCase01@3cce5371]" name="loginTest" class="rough.TestCase01"/>
        <method signature="TestFailure.testFail()[pri:0, instance:CustomListeners.TestFailure@6b09fb41]" name="testFail" class="CustomListeners.TestFailure"/>
        <method signature="TestCase03.regressionM01()[pri:0, instance:rough.TestCase03@5340477f]" name="regressionM01" class="rough.TestCase03"/>
        <method signature="TestCase03.regressionM02()[pri:0, instance:rough.TestCase03@5340477f]" name="regressionM02" class="rough.TestCase03"/>
        <method signature="TestCase03.validateTitle()[pri:0, instance:rough.TestCase03@5340477f]" name="validateTitle" class="rough.TestCase03"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="TestCase01.regTest()[pri:1, instance:rough.TestCase01@3cce5371]" name="regTest" class="rough.TestCase01"/>
        <method signature="TestFailure.testFail()[pri:0, instance:CustomListeners.TestFailure@6b09fb41]" name="testFail" class="CustomListeners.TestFailure"/>
        <method signature="TestCase03.validateTitle()[pri:0, instance:rough.TestCase03@5340477f]" name="validateTitle" class="rough.TestCase03"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2025-01-09T07:43:44Z" name="User Reg and login Test" finished-at="2025-01-09T07:43:44Z" duration-ms="30">
      <class name="rough.TestCase01">
        <test-method signature="regTest()[pri:1, instance:rough.TestCase01@3cce5371]" started-at="2025-01-09T07:43:44Z" name="regTest" finished-at="2025-01-09T07:43:44Z" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regTest -->
        <test-method signature="loginTest()[pri:0, instance:rough.TestCase01@3cce5371]" started-at="2025-01-09T07:43:44Z" name="loginTest" finished-at="2025-01-09T07:43:44Z" depends-on-methods="rough.TestCase01.regTest" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- rough.TestCase01 -->
    </test> <!-- User Reg and login Test -->
    <test started-at="2025-01-09T07:43:44Z" name="Failure Test for testing Listeners" finished-at="2025-01-09T07:43:44Z" duration-ms="4">
      <class name="CustomListeners.TestFailure">
        <test-method signature="testFail()[pri:0, instance:CustomListeners.TestFailure@6b09fb41]" started-at="2025-01-09T07:43:44Z" name="testFail" finished-at="2025-01-09T07:43:44Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing the tets to see the ITestListeners implementation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing the tets to see the ITestListeners implementation.
at org.testng.Assert.fail(Assert.java:96)
at CustomListeners.TestFailure.testFail(TestFailure.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail -->
      </class> <!-- CustomListeners.TestFailure -->
    </test> <!-- Failure Test for testing Listeners -->
    <test started-at="2025-01-09T07:43:44Z" name="Go to Home page and Next page test" finished-at="2025-01-09T07:43:44Z" duration-ms="0">
    </test> <!-- Go to Home page and Next page test -->
    <test started-at="2025-01-09T07:43:44Z" name="Regression test cases Test" finished-at="2025-01-09T07:43:44Z" duration-ms="11">
      <class name="rough.TestCase03">
        <test-method signature="regressionM01()[pri:0, instance:rough.TestCase03@5340477f]" started-at="2025-01-09T07:43:44Z" name="regressionM01" finished-at="2025-01-09T07:43:44Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regressionM01 -->
        <test-method signature="regressionM02()[pri:0, instance:rough.TestCase03@5340477f]" started-at="2025-01-09T07:43:44Z" name="regressionM02" finished-at="2025-01-09T07:43:44Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regressionM02 -->
        <test-method signature="validateTitle()[pri:0, instance:rough.TestCase03@5340477f]" started-at="2025-01-09T07:43:44Z" name="validateTitle" finished-at="2025-01-09T07:43:44Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [LeBloom.com] but found [LaBloom.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [LeBloom.com] but found [LaBloom.com]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at rough.TestCase03.validateTitle(TestCase03.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
      </class> <!-- rough.TestCase03 -->
    </test> <!-- Regression test cases Test -->
  </suite> <!-- Custom Listeners in TestNG -->
</testng-results>
